spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5456/javatoolbox?user=javatoolbox&password=p@ssw0rd
    driver-class-name: org.postgresql.Driver